version: '3'

volumes:
  postgres_volumes:

services:
  pg:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volumes:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: migrations/migrator.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg